In [2]:
from numpy import *
import numpy as np

def sigmoid(intZ):
    return 1.0/(1+exp(-intZ))

origin = np.loadtxt("/home/kj/下载/testSet.txt")

X = origin[:,:2].T
Y = origin[:,-1:]
w = np.zeros((2,1))
b = 0

for iter in range(1000):
    Z = np.dot(w.T,X)+b
    A = sigmoid(Z)
    dz = A - Y.T
    dw = np.dot(X,dz.T)/100
    db = np.sum(dz)/100
    print(dw)
    w = w - 0.1 * dw
    b = b - 0.1 * db


# def y_hat(x1,x2):    
#     if sigmoid(np.dot(w.T,[[x1],[x2]]) + b) > 0.5:
#         result = 1
#     else:
#         result = 0
#     return result
# count = 0
# for i in range(100):
#     if(y_hat(X[0][i],X[1][i]) - Y[i] != 0):
#         count += 1
# print(count)






[[ 0.02355558]
 [ 1.71974059]]
[[-0.03723409]
 [-0.48070444]]
[[-0.02320985]
 [ 0.00117125]]
[[-0.02262472]
 [ 0.02485035]]
[[-0.02279037]
 [ 0.0218768 ]]
[[-0.02285475]
 [ 0.0220935 ]]
[[-0.02292086]
 [ 0.02192063]]
[[-0.02297642]
 [ 0.02179529]]
[[-0.02302326]
 [ 0.02166518]]
[[-0.02306152]
 [ 0.02153646]]
[[-0.02309153]
 [ 0.02140844]]
[[-0.02311358]
 [ 0.02128121]]
[[-0.02312799]
 [ 0.02115476]]
[[-0.02313503]
 [ 0.02102911]]
[[-0.023135  ]
 [ 0.02090425]]
[[-0.02312818]
 [ 0.02078021]]
[[-0.02311485]
 [ 0.02065698]]
[[-0.02309526]
 [ 0.02053457]]
[[-0.02306969]
 [ 0.02041298]]
[[-0.02303839]
 [ 0.02029223]]
[[-0.02300162]
 [ 0.02017231]]
[[-0.0229596 ]
 [ 0.02005323]]
[[-0.02291259]
 [ 0.01993499]]
[[-0.02286081]
 [ 0.0198176 ]]
[[-0.02280449]
 [ 0.01970105]]
[[-0.02274385]
 [ 0.01958536]]
[[-0.02267909]
 [ 0.01947051]]
[[-0.02261042]
 [ 0.01935652]]
[[-0.02253804]
 [ 0.01924338]]
[[-0.02246214]
 [ 0.0191311 ]]
[[-0.02238292]
 [ 0.01901967]]
[[-0.02230054]
 [ 0.01890909]]
[[-0.022

 [ 0.00698283]]
[[-0.00576992]
 [ 0.00696612]]
[[-0.00574973]
 [ 0.00694949]]
[[-0.00572967]
 [ 0.00693296]]
[[-0.00570975]
 [ 0.0069165 ]]
[[-0.00568995]
 [ 0.00690014]]
[[-0.00567028]
 [ 0.00688385]]
[[-0.00565074]
 [ 0.00686765]]
[[-0.00563133]
 [ 0.00685153]]
[[-0.00561205]
 [ 0.0068355 ]]
[[-0.00559289]
 [ 0.00681954]]
[[-0.00557385]
 [ 0.00680367]]
[[-0.00555494]
 [ 0.00678787]]
[[-0.00553615]
 [ 0.00677216]]
[[-0.00551747]
 [ 0.00675652]]
[[-0.00549892]
 [ 0.00674096]]
[[-0.00548049]
 [ 0.00672548]]
[[-0.00546217]
 [ 0.00671008]]
[[-0.00544397]
 [ 0.00669475]]
[[-0.00542589]
 [ 0.0066795 ]]
[[-0.00540792]
 [ 0.00666433]]
[[-0.00539006]
 [ 0.00664923]]
[[-0.00537232]
 [ 0.0066342 ]]
[[-0.00535468]
 [ 0.00661925]]
[[-0.00533716]
 [ 0.00660437]]
[[-0.00531975]
 [ 0.00658956]]
[[-0.00530244]
 [ 0.00657483]]
[[-0.00528525]
 [ 0.00656017]]
[[-0.00526816]
 [ 0.00654558]]
[[-0.00525117]
 [ 0.00653106]]
[[-0.00523429]
 [ 0.0065166 ]]
[[-0.00521752]
 [ 0.00650222]]
[[-0.00520084]
 [ 0.006

In [37]:
from numpy import *
import numpy as np

def sigmoid(intZ):
    return 1.0/(1 + exp(-intZ))
def ReLU(intZ):
    for x in intZ:
        if x.any() < 0:
            x = 0
    return intZ

origin = np.loadtxt("/home/kj/下载/testSet.txt")
A_0 = origin[:,:2].T 
W_1 = np.random.randn(3,2)*0.01
b_1 = np.zeros((3,1))
W_2 = np.random.randn(2,3)*0.01
b_2 = np.zeros((2,1))
W_3 = np.random.randn(1,2)*0.01
b_3 = 0

Z_1 = np.dot(W_1 , A_0) + b_1
A_1 = ReLU(Z_1)
Z_2 = np.dot(W_2 , A_1) + b_2
A_2 = ReLU(Z_2)
Z_3 = np.dot(W_3 , A_2) + b_3
A_3 = sigmoid(Z_3)




In [7]:
f = open("/home/kj/下载/testSet.txt")
lines = f.readlines()
for line in lines:
    print(line)


-0.017612	14.053064	0

-1.395634	4.662541	1

-0.752157	6.538620	0

-1.322371	7.152853	0

0.423363	11.054677	0

0.406704	7.067335	1

0.667394	12.741452	0

-2.460150	6.866805	1

0.569411	9.548755	0

-0.026632	10.427743	0

0.850433	6.920334	1

1.347183	13.175500	0

1.176813	3.167020	1

-1.781871	9.097953	0

-0.566606	5.749003	1

0.931635	1.589505	1

-0.024205	6.151823	1

-0.036453	2.690988	1

-0.196949	0.444165	1

1.014459	5.754399	1

1.985298	3.230619	1

-1.693453	-0.557540	1

-0.576525	11.778922	0

-0.346811	-1.678730	1

-2.124484	2.672471	1

1.217916	9.597015	0

-0.733928	9.098687	0

-3.642001	-1.618087	1

0.315985	3.523953	1

1.416614	9.619232	0

-0.386323	3.989286	1

0.556921	8.294984	1

1.224863	11.587360	0

-1.347803	-2.406051	1

1.196604	4.951851	1

0.275221	9.543647	0

0.470575	9.332488	0

-1.889567	9.542662	0

-1.527893	12.150579	0

-1.185247	11.309318	0

-0.445678	3.297303	1

1.042222	6.105155	1

-0.618787	10.320986	0

1.152083	0.548467	1

0.828534	2.676045	1

-1.237728	10.5490

In [79]:
'''
Created on Oct 27, 2010
Logistic Regression Working Module
@author: Peter
'''
from numpy import *

def loadDataSet():
    dataMat = []; labelMat = []
    fr = open('testSet.txt')
    for line in fr.readlines():
        lineArr = line.strip().split()
        dataMat.append([1.0, float(lineArr[0]), float(lineArr[1])])
        labelMat.append(int(lineArr[2]))
    return dataMat,labelMat

def sigmoid(inX):
    return 1.0/(1+exp(-inX))

def gradAscent(dataMatIn, classLabels):
    dataMatrix = mat(dataMatIn)             #convert to NumPy matrix
    labelMat = mat(classLabels).transpose() #convert to NumPy matrix
    m,n = shape(dataMatrix)
    alpha = 0.001
    maxCycles = 500
    weights = ones((n,1))
    for k in range(maxCycles):              #heavy on matrix operations
        h = sigmoid(dataMatrix*weights)     #matrix mult
        error = (labelMat - h)              #vector subtraction
        weights = weights + alpha * dataMatrix.transpose()* error #matrix mult
    return weights

def plotBestFit(weights):
    import matplotlib.pyplot as plt
    dataMat,labelMat=loadDataSet()
    dataArr = array(dataMat)
    n = shape(dataArr)[0] 
    xcord1 = []; ycord1 = []
    xcord2 = []; ycord2 = []
    for i in range(n):
        if int(labelMat[i])== 1:
            xcord1.append(dataArr[i,1]); ycord1.append(dataArr[i,2])
        else:
            xcord2.append(dataArr[i,1]); ycord2.append(dataArr[i,2])
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.scatter(xcord1, ycord1, s=30, c='red', marker='s')
    ax.scatter(xcord2, ycord2, s=30, c='green')
    x = arange(-3.0, 3.0, 0.1)
    y = (-weights[0]-weights[1]*x)/weights[2]
    ax.plot(x, y)
    plt.xlabel('X1'); plt.ylabel('X2');
    plt.show()

def stocGradAscent0(dataMatrix, classLabels):
    m,n = shape(dataMatrix)
    alpha = 0.01
    weights = ones(n)   #initialize to all ones
    for i in range(m):
        h = sigmoid(sum(dataMatrix[i]*weights))
        error = classLabels[i] - h
        weights = weights + alpha * error * dataMatrix[i]
    return weights

def stocGradAscent1(dataMatrix, classLabels, numIter=150):
    m,n = shape(dataMatrix)
    weights = ones(n)   #initialize to all ones
    for j in range(numIter):
        dataIndex = range(m)
        for i in range(m):
            alpha = 4/(1.0+j+i)+0.0001    #apha decreases with iteration, does not 
            randIndex = int(random.uniform(0,len(dataIndex)))#go to 0 because of the constant
            h = sigmoid(sum(dataMatrix[randIndex]*weights))
            error = classLabels[randIndex] - h
            weights = weights + alpha * error * dataMatrix[randIndex]
            del(dataIndex[randIndex])
    return weights

def classifyVector(inX, weights):
    prob = sigmoid(sum(inX*weights))
    if prob > 0.5: return 1.0
    else: return 0.0

def colicTest():
    frTrain = open('horseColicTraining.txt'); frTest = open('horseColicTest.txt')
    trainingSet = []; trainingLabels = []
    for line in frTrain.readlines():
        currLine = line.strip().split('\t')
        lineArr =[]
        for i in range(21):
            lineArr.append(float(currLine[i]))
        trainingSet.append(lineArr)
        trainingLabels.append(float(currLine[21]))
    trainWeights = stocGradAscent1(array(trainingSet), trainingLabels, 1000)
    errorCount = 0; numTestVec = 0.0
    for line in frTest.readlines():
        numTestVec += 1.0
        currLine = line.strip().split('\t')
        lineArr =[]
        for i in range(21):
            lineArr.append(float(currLine[i]))
        if int(classifyVector(array(lineArr), trainWeights))!= int(currLine[21]):
            errorCount += 1
    errorRate = (float(errorCount)/numTestVec)
    print "the error rate of this test is: %f" % errorRate
    return errorRate

def multiTest():
    numTests = 10; errorSum=0.0
    for k in range(numTests):
        errorSum += colicTest()
    print "after %d iterations the average error rate is: %f" % (numTests, errorSum/float(numTests))